//
// Created by Hans Johnson on 2026-02-14.
//

#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkBinaryThresholdImageFilter.h"


int main(int argc, char* argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

  // Define image type
  using PixelType = short;
  using ImageType = itk::Image<PixelType, 3>;

  // Read input image
  auto reader = itk::ImageFileReader<ImageType>::New();
  reader->SetFileName(inputVolume);

  // Set up threshold filter
  auto filter = itk::BinaryThresholdImageFilter<ImageType, ImageType>::New();
  filter->SetInput(reader->GetOutput());
  filter->SetLowerThreshold(static_cast<PixelType>(lowThreshold));
  filter->SetUpperThreshold(static_cast<PixelType>(highThreshold));
  filter->SetInsideValue(static_cast<PixelType>(insideValue));
  filter->SetOutsideValue(static_cast<PixelType>(outsideValue));

  // Write output image
  auto writer = itk::ImageFileWriter<ImageType>::New();
  writer->SetFileName(outputVolume);
  writer->SetInput(filter->GetOutput());

  try
  {
    writer->Update();
  }
  catch(const itk::ExceptionObject& err)
  {
    std::cerr << "Error: " << err << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
